import type { Wilaya } from '../types';

export const WILAYAS: Wilaya[] = [
  { code: 1, name_ar: 'أدرار', name_en: 'Adrar', shipping_cost: 800, home_delivery_cost: 1200 },
  { code: 2, name_ar: 'الشلف', name_en: 'Chlef', shipping_cost: 400, home_delivery_cost: 600 },
  { code: 3, name_ar: 'الأغواط', name_en: 'Laghouat', shipping_cost: 600, home_delivery_cost: 900 },
  { code: 4, name_ar: 'أم البواقي', name_en: 'Oum El Bouaghi', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 5, name_ar: 'باتنة', name_en: 'Batna', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 6, name_ar: 'بجاية', name_en: 'Béjaïa', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 7, name_ar: 'بسكرة', name_en: 'Biskra', shipping_cost: 600, home_delivery_cost: 900 },
  { code: 8, name_ar: 'بشار', name_en: 'Béchar', shipping_cost: 700, home_delivery_cost: 1000 },
  { code: 9, name_ar: 'البليدة', name_en: 'Blida', shipping_cost: 350, home_delivery_cost: 500 },
  { code: 10, name_ar: 'البويرة', name_en: 'Bouira', shipping_cost: 400, home_delivery_cost: 600 },
  { code: 11, name_ar: 'تمنراست', name_en: 'Tamanrasset', shipping_cost: 1000, home_delivery_cost: 1400 },
  { code: 12, name_ar: 'تبسة', name_en: 'Tébessa', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 13, name_ar: 'تلمسان', name_en: 'Tlemcen', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 14, name_ar: 'تيارت', name_en: 'Tiaret', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 15, name_ar: 'تيزي وزو', name_en: 'Tizi Ouzou', shipping_cost: 450, home_delivery_cost: 650 },
  { code: 16, name_ar: 'الجزائر', name_en: 'Alger', shipping_cost: 300, home_delivery_cost: 400 },
  { code: 17, name_ar: 'الجلفة', name_en: 'Djelfa', shipping_cost: 600, home_delivery_cost: 900 },
  { code: 18, name_ar: 'جيجل', name_en: 'Jijel', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 19, name_ar: 'سطيف', name_en: 'Sétif', shipping_cost: 450, home_delivery_cost: 650 },
  { code: 20, name_ar: 'سعيدة', name_en: 'Saïda', shipping_cost: 550, home_delivery_cost: 800 },
  { code: 21, name_ar: 'سكيكدة', name_en: 'Skikda', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 22, name_ar: 'سيدي بلعباس', name_en: 'Sidi Bel Abbès', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 23, name_ar: 'عنابة', name_en: 'Annaba', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 24, name_ar: 'قالمة', name_en: 'Guelma', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 25, name_ar: 'قسنطينة', name_en: 'Constantine', shipping_cost: 450, home_delivery_cost: 650 },
  { code: 26, name_ar: 'المدية', name_en: 'Médéa', shipping_cost: 400, home_delivery_cost: 600 },
  { code: 27, name_ar: 'مستغانم', name_en: 'Mostaganem', shipping_cost: 450, home_delivery_cost: 650 },
  { code: 28, name_ar: 'المسيلة', name_en: "M'Sila", shipping_cost: 500, home_delivery_cost: 700 },
  { code: 29, name_ar: 'معسكر', name_en: 'Mascara', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 30, name_ar: 'ورقلة', name_en: 'Ouargla', shipping_cost: 700, home_delivery_cost: 1000 },
  { code: 31, name_ar: 'وهران', name_en: 'Oran', shipping_cost: 450, home_delivery_cost: 650 },
  { code: 32, name_ar: 'البيض', name_en: 'El Bayadh', shipping_cost: 700, home_delivery_cost: 1000 },
  { code: 33, name_ar: 'إليزي', name_en: 'Illizi', shipping_cost: 1000, home_delivery_cost: 1400 },
  { code: 34, name_ar: 'برج بوعريريج', name_en: 'Bordj Bou Arréridj', shipping_cost: 450, home_delivery_cost: 650 },
  { code: 35, name_ar: 'بومرداس', name_en: 'Boumerdès', shipping_cost: 350, home_delivery_cost: 500 },
  { code: 36, name_ar: 'الطارف', name_en: 'El Tarf', shipping_cost: 550, home_delivery_cost: 800 },
  { code: 37, name_ar: 'تندوف', name_en: 'Tindouf', shipping_cost: 1000, home_delivery_cost: 1400 },
  { code: 38, name_ar: 'تيسمسيلت', name_en: 'Tissemsilt', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 39, name_ar: 'الوادي', name_en: 'El Oued', shipping_cost: 700, home_delivery_cost: 1000 },
  { code: 40, name_ar: 'خنشلة', name_en: 'Khenchela', shipping_cost: 550, home_delivery_cost: 800 },
  { code: 41, name_ar: 'سوق أهراس', name_en: 'Souk Ahras', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 42, name_ar: 'تيبازة', name_en: 'Tipaza', shipping_cost: 350, home_delivery_cost: 500 },
  { code: 43, name_ar: 'ميلة', name_en: 'Mila', shipping_cost: 450, home_delivery_cost: 650 },
  { code: 44, name_ar: 'عين الدفلى', name_en: 'Aïn Defla', shipping_cost: 400, home_delivery_cost: 600 },
  { code: 45, name_ar: 'النعامة', name_en: 'Naâma', shipping_cost: 700, home_delivery_cost: 1000 },
  { code: 46, name_ar: 'عين تموشنت', name_en: 'Aïn Témouchent', shipping_cost: 500, home_delivery_cost: 700 },
  { code: 47, name_ar: 'غرداية', name_en: 'Ghardaïa', shipping_cost: 600, home_delivery_cost: 900 },
  { code: 48, name_ar: 'غليزان', name_en: 'Relizane', shipping_cost: 500, home_delivery_cost: 700 },
];

export const PAYMENT_METHODS = [
  { id: 'cod', name_ar: 'الدفع عند الاستلام', name_en: 'Cash on Delivery' },
  { id: 'baridimob', name_ar: 'بريدي موب', name_en: 'BaridiMob' },
  { id: 'cib', name_ar: 'بطاقة CIB', name_en: 'CIB Card' },
  { id: 'edahabia', name_ar: 'بطاقة الذهبية', name_en: 'Edahabia Card' },
];
